version: "3.8"

services:
  redis-server:
    image: redis
    ports:
    - "6379:6379"
    container_name: redir-server

  node-app:
    build:
      dockerfile: node.dockerfile
      context: ./nodeapp
    container_name: node-app
    ports:
    - "8081:8081"
    depends_on:
      - redis-server